module.exports = 

{  
    "city":{  
       "id":1010569,
       "city":"Cairo",
       "lat":30.06,
       "lon":31.25,
       "state":"",
       "country":"eg",
       "zip":"meetup1",
       "member_count":2817
    },
    "events":[  
       {  
          "created":1534340053000,
          "duration":14400000,
          "id":"253811079",
          "name":"Pizza on Chatbots at Seedspace Cairo",
          "status":"upcoming",
          "time":1536400800000,
          "local_date":"2018-09-08",
          "local_time":"12:00",
          "updated":1535386974000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":24,
          "venue":{  
             "id":25912694,
             "name":"Seedspace Cairo",
             "lat":29.956979751586914,
             "lon":31.265277862548828,
             "repinned":false,
             "address_1":"Sarayat Al Gharbeyah Al Maadi",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1523795153000,
             "name":"IBM Cloud Egypt",
             "id":28170754,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"IBM-Cloud-Egypt",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/IBM-Cloud-Egypt/events/253811079/",
          "description":"<p>Embrace the Chatbot craze and learn all about IBM's Watson Assistant service and create highly intelligent chat-bots that can streamline the way you engage with customers, partners and employees.</p> <p>Attend this workshop and build robust, reliable, enterprise-grade virtual assistants to transform the way you do business and easily integrate it with multiple social and messaging channels including Slack, Facebook and Twilio.</p> <p>Workshop Outline:<br/>· Quick overview about IBM Cloud and its Services<br/>· Watson overview.<br/>· Designing Your Bot<br/>· Conversation Service Tool<br/>· How to integrate it with the front end<br/>· Adding other services to the Bot<br/>· Integrating the Bot with the back-end services</p> <p>**UPDATE**<br/>Kindly fill this form: <a href=\"https://seedsta.rs/2ocRAb0\" class=\"linkified\">https://seedsta.rs/2ocRAb0</a> and be certain of your attendance as there are only a few seats remaining.</p> ",
          "visibility":"public"
       },
       {  
          "created":1532983478000,
          "duration":7200000,
          "id":"253315710",
          "name":"SWAP* Project priority for Support - مشروع التبادل الحر الأولوية",
          "status":"upcoming",
          "time":1535823000000,
          "local_date":"2018-09-01",
          "local_time":"19:30",
          "updated":1533740683000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":19,
          "group":{  
             "created":1262040162000,
             "name":"I am Happy Project - Cairo, Egypt",
             "id":1574048,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"I-am-Happy-Project-Cairo-Egypt",
             "who":"Happy People",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/I-am-Happy-Project-Cairo-Egypt/events/253315710/",
          "description":"<p>السعادة ليست في الحصول علي الأشياء إنما في المشاركة. نحن نكسب العيش من خلال ما نحصل عليه ، ولكننا نبني حياة من خلال ما نقدمه.<br/>\u201cHappiness is not so much in having as sharing. We make a living by what we get, but we make a life by what we give.\u201d<br/>\u2014 Norman MacEwen<br/>بعد سنتين من ميلاد مشروع التبادل الحر<br/>It's been two years since swap* the free exchange project was born<br/>سنتين مليانين حب وعطاء<br/>Two years full of love and giving<br/>مجتمعنا بيكبر بمساهمة كل واحد فينا<br/>Our community grows with the contribution of each member<br/>مشروعنا النهارده كان ف الاصل فكره 😃.<br/>Our project was originated from an idea<br/>فكره هدفها اننا نخرج برة سجن المادية<br/>With the goal Breaking free out of the materiality prison<br/>فكرة مبنية علي قناعة أن أفضل الأشياء في الحياة تأتي بلا مقابل<br/>Inspired by the fact that best things in life are fre<br/>فكرة هدفها حياه<br/>Our goal is to make a life not just make a living<br/>شارك معانا ف لقاء المتطوعين<br/>Join our alive community<br/>نتشارك شغفنا<br/>To share the passion<br/>نتشارك الحــــــــيـــــــــــــاه<br/>To share \"life\"</p> <p>Make SWAP* a priority for you to support<br/>إجعل مشروع التبادل الحر له أولوية ف الدعم</p> <p>ننتظركم جميعاً من أجل التطوير و التننمية المستدامة</p> <p>Waiting you all</p> ",
          "visibility":"public"
       },
       {  
          "created":1533486754000,
          "duration":10800000,
          "id":"lnzbcqyxmbgb",
          "name":"SWAP*: Anti - August Depression",
          "status":"upcoming",
          "time":1536082200000,
          "local_date":"2018-09-04",
          "local_time":"19:30",
          "updated":1533486754000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":1,
          "venue":{  
             "id":1093236,
             "name":"Cairo",
             "lat":30.064741134643555,
             "lon":31.249509811401367,
             "repinned":false,
             "address_1":"Cairo",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1262040162000,
             "name":"I am Happy Project - Cairo, Egypt",
             "id":1574048,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"I-am-Happy-Project-Cairo-Egypt",
             "who":"Happy People",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/I-am-Happy-Project-Cairo-Egypt/events/253921688/",
          "description":"<p>Anti - August Depression - ضد إكتئاب أغسطس</p> <p>Full Course \"4 Classes\" to Know how you can deal with August<br/>تدريب متكامل \"4 مرات تدريب\" لمعرفة كيف تتعامل مع أغسطس</p> <p>\"يوجد شق نفسي للتحدث عن علوم النفس و شق تدريبي للتمارين المفيد من اليوجا و التنفس و علم الإنعكاس - الريفلكسولوجي \"<br/>Yoga - Meditation - Reflexology - Psychology</p> <p>تدريب و إستشفاء في المعادي - Training and Healing in Maadi</p> <p>للحجز والإستعلام يرجى إرسال رسالة نصية أو على الواتس اب : 01006327285<br/>For Reservation and Information kindly send a message on SMS or Whatsapp : 01006327285</p> <p>قيمة المرة الواحدة للحدث التدريب = 125 جم .<br/>\"نظراً لأن العدد محدود\"<br/>التدريب كاملاً : أربعة مرات بمبلغ 400 جم تدفع مرة واحدة و لا تسترد .</p> <p>Fees of Course \" one class\" = EGP 125<br/>Fees for \"4 Classes \" = EGP 400</p> <p>Be ready for Energy</p> ",
          "visibility":"public"
       },
       {  
          "created":1533486754000,
          "duration":10800000,
          "id":"lnzbcqyxmbpb",
          "name":"SWAP*: Anti - August Depression",
          "status":"upcoming",
          "time":1536687000000,
          "local_date":"2018-09-11",
          "local_time":"19:30",
          "updated":1533486754000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":1,
          "venue":{  
             "id":1093236,
             "name":"Cairo",
             "lat":30.064741134643555,
             "lon":31.249509811401367,
             "repinned":false,
             "address_1":"Cairo",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1262040162000,
             "name":"I am Happy Project - Cairo, Egypt",
             "id":1574048,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"I-am-Happy-Project-Cairo-Egypt",
             "who":"Happy People",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/I-am-Happy-Project-Cairo-Egypt/events/254011987/",
          "description":"<p>Anti - August Depression - ضد إكتئاب أغسطس</p> <p>Full Course \"4 Classes\" to Know how you can deal with August<br/>تدريب متكامل \"4 مرات تدريب\" لمعرفة كيف تتعامل مع أغسطس</p> <p>\"يوجد شق نفسي للتحدث عن علوم النفس و شق تدريبي للتمارين المفيد من اليوجا و التنفس و علم الإنعكاس - الريفلكسولوجي \"<br/>Yoga - Meditation - Reflexology - Psychology</p> <p>تدريب و إستشفاء في المعادي - Training and Healing in Maadi</p> <p>للحجز والإستعلام يرجى إرسال رسالة نصية أو على الواتس اب : 01006327285<br/>For Reservation and Information kindly send a message on SMS or Whatsapp : 01006327285</p> <p>قيمة المرة الواحدة للحدث التدريب = 125 جم .<br/>\"نظراً لأن العدد محدود\"<br/>التدريب كاملاً : أربعة مرات بمبلغ 400 جم تدفع مرة واحدة و لا تسترد .</p> <p>Fees of Course \" one class\" = EGP 125<br/>Fees for \"4 Classes \" = EGP 400</p> <p>Be ready for Energy</p> ",
          "visibility":"public"
       },
       {  
          "created":1534340370000,
          "duration":7200000,
          "id":"253811190",
          "name":"Egypt Cognitive Day",
          "status":"upcoming",
          "time":1538154000000,
          "local_date":"2018-09-28",
          "local_time":"19:00",
          "updated":1534340370000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":6,
          "venue":{  
             "id":25812292,
             "name":"Nile University TechSpace",
             "lat":30.043420791625977,
             "lon":31.097536087036133,
             "repinned":false,
             "address_1":"Nile University",
             "address_2":"Arab El-Sheikh Zeid",
             "city":"Giza",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1523795153000,
             "name":"IBM Cloud Egypt",
             "id":28170754,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"IBM-Cloud-Egypt",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/IBM-Cloud-Egypt/events/253811190/",
          "description":"<p>The Event will provide a deep-dive overview of IBM\u2019s Cloud platform and technology with a reflective explanation of its highly positive impact on startups\u2019 performance and improvement. Attendees will not just listen to IBM\u2019s vision and programs regarding the cloud revolution, but will also get the chance to use the tools and services themselves</p> ",
          "visibility":"public"
       },
       {  
          "created":1534012888000,
          "duration":10800000,
          "id":"trrwcqyxlbnc",
          "name":"Thursday night Language Exchange - meet and make new Friends.",
          "rsvp_limit":60,
          "status":"upcoming",
          "time":1535648400000,
          "local_date":"2018-08-30",
          "local_time":"19:00",
          "updated":1534601558000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":32,
          "venue":{  
             "id":25389105,
             "name":"garage coworking space ",
             "lat":30.04355239868164,
             "lon":31.23778533935547,
             "repinned":true,
             "address_1":"31 Mohamed Mahmoud st, 5th floor ",
             "city":"Cairo ",
             "country":"EG",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1483468269000,
             "name":"Cairo EASL Community",
             "id":21757493,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"CairoEASLCommuinty",
             "who":"Friends",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/CairoEASLCommuinty/events/253710544/",
          "description":"<p>''Let's do it again and again, join us to have a great time to Exchange and meet new friends which you can exchange more than languages, books, career advice, ideas, and make really good friends.''</p> <p>Meetup facebook group:<br/><a href=\"https://www.facebook.com/groups/CairoEASL\" class=\"linkified\">https://www.facebook.com/groups/CairoEASL</a></p> <p>Meetup charges:<br/>The meetup is Free of charge.</p> <p>Coworking Space charges:<br/>15-20 LE Max for each Person/3 hrs (including Hot drink)</p> <p>Location info:<br/>31 Mohamed Mahmoud St, in the front of AUC Tahrir. 5th floor.</p> <p>Location link:<br/><a href=\"https://goo.gl/maps/RDRadAYyKvq\" class=\"linkified\">https://goo.gl/maps/RDRadAYyKvq</a></p> <p>For more inquiries, WhatsApp me at +201120260006</p> <p>Hamed</p> ",
          "how_to_find_us":"\"The Same building of Cilantro Cafe\"",
          "visibility":"public"
       },
       {  
          "created":1534601557000,
          "duration":10800000,
          "id":"trrwcqyxmbjb",
          "name":"Thursday night Language Exchange - meet and make new Friends.",
          "rsvp_limit":60,
          "status":"upcoming",
          "time":1536253200000,
          "local_date":"2018-09-06",
          "local_time":"19:00",
          "updated":1534601557000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":7,
          "venue":{  
             "id":25389105,
             "name":"garage coworking space ",
             "lat":30.04262351989746,
             "lon":31.242721557617188,
             "repinned":false,
             "address_1":"31 Mohamed Mahmoud st, 5th floor ",
             "city":"Cairo ",
             "country":"EG",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1483468269000,
             "name":"Cairo EASL Community",
             "id":21757493,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"CairoEASLCommuinty",
             "who":"Friends",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/CairoEASLCommuinty/events/253900760/",
          "description":"<p>''Let's do it again and again, join us to have a great time to Exchange and meet new friends which you can exchange more than languages, books, career advice, ideas, and make really good friends.''</p> <p>Meetup facebook group:<br/><a href=\"https://www.facebook.com/groups/CairoEASL\" class=\"linkified\">https://www.facebook.com/groups/CairoEASL</a></p> <p>Meetup charges:<br/>The meetup is Free of charge.</p> <p>Coworking Space charges:<br/>15-20 LE Max for each Person/3 hrs (including Hot drink)</p> <p>Location info:<br/>31 Mohamed Mahmoud St, in the front of AUC Tahrir. 5th floor.</p> <p>Location link:<br/><a href=\"https://goo.gl/maps/RDRadAYyKvq\" class=\"linkified\">https://goo.gl/maps/RDRadAYyKvq</a></p> <p>For more inquiries, WhatsApp me at +201120260006</p> <p>Hamed</p> ",
          "how_to_find_us":"\"The Same building of Cilantro Cafe\"",
          "visibility":"public"
       },
       {  
          "created":1531337416000,
          "duration":10800000,
          "id":"trrwcqyxmbkc",
          "name":"Thursday night Language Exchange - meet and make new Friends.",
          "rsvp_limit":60,
          "status":"upcoming",
          "time":1538067600000,
          "local_date":"2018-09-27",
          "local_time":"19:00",
          "updated":1534601558000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":4,
          "venue":{  
             "id":25389105,
             "name":"garage coworking space ",
             "lat":30.04355239868164,
             "lon":31.23778533935547,
             "repinned":true,
             "address_1":"31 Mohamed Mahmoud st, 5th floor ",
             "city":"Cairo ",
             "country":"EG",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1483468269000,
             "name":"Cairo EASL Community",
             "id":21757493,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"CairoEASLCommuinty",
             "who":"Friends",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/CairoEASLCommuinty/events/253266575/",
          "description":"<p>''Let's do it again and again, join us to have a great time to Exchange and meet new friends which you can exchange more than languages, books, career advice, ideas, and make really good friends.''</p> <p>Meetup facebook group:<br/><a href=\"https://www.facebook.com/groups/CairoEASL\" class=\"linkified\">https://www.facebook.com/groups/CairoEASL</a></p> <p>Meetup charges:<br/>The meetup is Free of charge.</p> <p>Coworking Space charges:<br/>15-20 LE Max for each Person/3 hrs (including Hot drink)</p> <p>Location info:<br/>31 Mohamed Mahmoud St, in the front of AUC Tahrir. 5th floor.</p> <p>Location link:<br/><a href=\"https://goo.gl/maps/RDRadAYyKvq\" class=\"linkified\">https://goo.gl/maps/RDRadAYyKvq</a></p> <p>For more inquiries, WhatsApp me at +201120260006</p> <p>Hamed</p> ",
          "how_to_find_us":"\"The Same building of Cilantro Cafe\"",
          "visibility":"public"
       },
       {  
          "created":1534672939000,
          "duration":7200000,
          "id":"253917690",
          "name":"Blockchain: A Use Case Demo & Workshop (Part 2)",
          "rsvp_limit":50,
          "status":"upcoming",
          "time":1535817600000,
          "local_date":"2018-09-01",
          "local_time":"18:00",
          "updated":1534673325000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":26,
          "venue":{  
             "id":24601838,
             "name":"Mushtarak",
             "lat":30.040748596191406,
             "lon":31.202030181884766,
             "repinned":false,
             "address_1":"37, Amman Street, Dokki",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1431710779000,
             "name":"Cairo Bitcoin Meetup",
             "id":18600251,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"BitcoinCairo",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/BitcoinCairo/events/253917690/",
          "description":"<p>We are delighted to announce that Eng. Fady Ibrahim will be joining us again for another demo and workshop. Fady is a software developer and educator for mobile, cloud, and network courses. He obtained a Master of Science in Computer Engineering, and holds the badge of IBM Blockchain Developer.</p> <p>The meetup will be divided into 2 parts:</p> <p>**Part 1**<br/>In this part we will discuss a background about blockchain technology. Topics covered include:<br/>Blockchain<br/>Business Network<br/>Smart Contracts<br/>Hyperledger Fabric<br/>Hyperledger Composer</p> <p>**Part 2**<br/>Blockchain workshop for developers. This part is targeted towards developers looking to get an introduction about blockchain technology using a live demo. Topics covered include:</p> <p>Deploying Business Network<br/>Adding Participants, Assets, and Transactions</p> <p>Models :: Hyperledger Composer Modeling Language<br/>Permissions :: Access Control List<br/>Logic :: Java Script</p> <p>NOTE: If you intend to participate in the workshop, you will need a laptop to apply the steps.</p> <p>Date: Saturday, September 1st, 2018<br/>Time: 6:00-8:00 PM<br/>Location: Mushtarak</p> <p>37, Amman Street, Dokki, Giza (off of Mohi El Din Abu El Ezz Street).<br/>2nd floor.</p> <p>Map: <a href=\"https://goo.gl/maps/39h4pCkfLFy\" class=\"linkified\">https://goo.gl/maps/39h4pCkfLFy</a></p> <p>االعنوان: ٣٧ شارع عمان، متفرع من شارع محي الدين أبو العز، الدقي<br/>الدور الثاني</p> <p>أقرب محطة مترو هي البحوث</p> <p>خريطة (<a href=\"https://goo.gl/maps/39h4pCkfLFy\" class=\"linkified\">https://goo.gl/maps/39h4pCkfLFy</a>)</p> <p>Attendance is free with limited spaces available. RSVP to confirm your seat.</p> <p>Event Agenda</p> <p>6:00pm-7:00pm: Part 1 - Introduction to Blockchain<br/>7:00pm-7:15pm: Break<br/>7:15pm-8:00pm: Part 2 - Demo and workshop</p> ",
          "how_to_find_us":"2nd floor. 37, Amman Street, Dokki, Giza (off of Mohi El Din Abu El Ezz Street). ",
          "visibility":"public"
       },
       {  
          "created":1535170590000,
          "duration":10800000,
          "id":"254090789",
          "name":"مناقشة كتاب بيرة في نادي البلياردو للكاتب وجية غالي",
          "status":"upcoming",
          "time":1536422400000,
          "local_date":"2018-09-08",
          "local_time":"18:00",
          "updated":1535170590000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":6,
          "venue":{  
             "id":21970552,
             "name":"falak Center",
             "lat":0.0,
             "lon":0.0,
             "repinned":false,
             "address_1":"7 Gamal Eldin Abou El Mahasen st. , Garden City , Cairo, eg",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1388107240000,
             "name":"Cairo Book Club",
             "id":11577592,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Book-Club",
             "who":"Book Worms",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Book-Club/events/254090789/",
          "description":"<p>لينك تحميل الكتاب كـ PDF<br/><a href=\"http://www.bookleaks.com/files/fhrst3/00632.pdf\" class=\"linkified\">http://www.bookleaks.com/files/fhrst3/00632.pdf</a></p> ",
          "visibility":"public"
       },
       {  
          "created":1532617832000,
          "duration":7200000,
          "id":"tcxjbqyxlbpc",
          "name":"Meet New People ",
          "rsvp_limit":10,
          "status":"upcoming",
          "time":1535734800000,
          "local_date":"2018-08-31",
          "local_time":"19:00",
          "updated":1532617832000,
          "utc_offset":7200000,
          "waitlist_count":18,
          "yes_rsvp_count":10,
          "group":{  
             "created":1532617444000,
             "name":"Meetup Cairo",
             "id":29358533,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Meetup-Cairo",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Meetup-Cairo/events/253675630/",
          "description":"<p>Meet New people<br/>Create New friendships<br/>Share Your Experience<br/>let's Do It :)</p> ",
          "visibility":"public"
       },
       {  
          "created":1532617832000,
          "duration":7200000,
          "id":"tcxjbqyxmbkb",
          "name":"Meet New People ",
          "rsvp_limit":10,
          "status":"upcoming",
          "time":1536339600000,
          "local_date":"2018-09-07",
          "local_time":"19:00",
          "updated":1532617832000,
          "utc_offset":7200000,
          "waitlist_count":7,
          "yes_rsvp_count":10,
          "group":{  
             "created":1532617444000,
             "name":"Meetup Cairo",
             "id":29358533,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Meetup-Cairo",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Meetup-Cairo/events/253500396/",
          "description":"<p>Meet New people<br/>Create New friendships<br/>Share Your Experience<br/>let's Do It :)</p> ",
          "visibility":"public"
       },
       {  
          "created":1535122272000,
          "duration":32400000,
          "id":"254070409",
          "name":"Royal Yoga & Energy",
          "status":"upcoming",
          "time":1536303600000,
          "local_date":"2018-09-07",
          "local_time":"09:00",
          "updated":1535214943000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":5,
          "group":{  
             "created":1455120743000,
             "name":"Cairo Language Freaks",
             "id":19550132,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Language-Freaks",
             "who":"language freak",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Language-Freaks/events/254070409/",
          "description":"<p>This event just for people whose appreciate a royal lifestyle</p> <p>هذا الحدث فقط للأشخاص الذين يقدرون الحياة الملكية</p> <p>أولاً : يجب التسجل لحضور الحدث و إعلامنا بالعدد المرافق لك / لكي :<br/>Firstly : Registration forum :<br/><a href=\"https://docs.google.com/forms/d/1Oi7uhHGq-iyhHIo9KBft7lkgspUkGjihwLOEdknFwqY/prefill\" class=\"linkified\">https://docs.google.com/forms/d/1Oi7uhHGq-iyhHIo9KBft7lkgspUkGjihwLOEdknFwqY/prefill</a></p> <p>ثانياً : الأنشطة داخل نادي محمد علي الملكي :<br/>Secondly : Activities inside Mohamed Ali Royal Club :<br/>- التجمع الساعة 9 صباحاً أمام محطة مترو المنيب ثم التحرك إلى النادي .<br/>- البداية مع اليوجا و الطاقة صباحاً عند الوصول .<br/>- استخدام حمام السباحة و الجاكوزي و عمل بعض الأنشطة بالقرب من نهر النيل .<br/>- العودة الى تمارين اليوجا و التأمل و الإسترخاء .<br/>- مشاهدة الغروب .<br/>ملاحظة : ممنوع إصطحاب الأغذية و المشروبات من خارج النادي .</p> <p>- Gathering at 9:00 in front of the Monieb Metro station and then move to head the club.<br/>- Start with Yoga and energy on arrival.<br/>of Nile River.<br/>- Return to yoga, meditation and relaxation exercises.<br/>- Watch the sunset.<br/>Note: Food and drinks are not allowed to bring from outside the club.</p> <p>(Yoga , Meditation , Reflexology )</p> <p>Location of Monieb Metro station - موقع محطة مترو المنيب<br/><a href=\"https://goo.gl/maps/w1vWFzgMDC92\" class=\"linkified\">https://goo.gl/maps/w1vWFzgMDC92</a></p> <p>يمكنك ارسال رسالة نصية او واتس اب بعد التسجيل اولاً بالاسم و العدد :[masked]<br/>Yo can send a message SMS or Whats App. after registration forum :[masked]</p> <p>قضاء هذا اليوم الملئ بالأنشطة برسوم 400 جم شاملة الدخول و الإستمتاع بالأنشطة .<br/>Fees for Entrance and activities : EGP 400</p> <p>For any Further information :[masked]<br/>لأي إستفسار يرجى الإتصال على رقم :[masked]</p> ",
          "visibility":"public"
       },
       {  
          "created":1532617832000,
          "duration":7200000,
          "id":"tcxjbqyxmbsb",
          "name":"Meet New People ",
          "rsvp_limit":10,
          "status":"upcoming",
          "time":1536944400000,
          "local_date":"2018-09-14",
          "local_time":"19:00",
          "updated":1532617832000,
          "utc_offset":7200000,
          "waitlist_count":4,
          "yes_rsvp_count":10,
          "group":{  
             "created":1532617444000,
             "name":"Meetup Cairo",
             "id":29358533,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Meetup-Cairo",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Meetup-Cairo/events/253845934/",
          "description":"<p>Meet New people<br/>Create New friendships<br/>Share Your Experience<br/>let's Do It :)</p> ",
          "visibility":"public"
       },
       {  
          "created":1534431725000,
          "duration":10800000,
          "id":"253844497",
          "name":"Automation of API Testing using REST Assured",
          "rsvp_limit":50,
          "status":"upcoming",
          "time":1536937200000,
          "local_date":"2018-09-14",
          "local_time":"17:00",
          "updated":1534692283000,
          "utc_offset":7200000,
          "waitlist_count":15,
          "yes_rsvp_count":50,
          "group":{  
             "created":1493243139000,
             "name":"Cairo Testing Meetup",
             "id":23446514,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Testing-Meetup",
             "who":"Awesome Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Testing-Meetup/events/253844497/",
          "description":"<p>To be announced.</p> ",
          "visibility":"public"
       },
       {  
          "created":1535123783000,
          "duration":212400000,
          "id":"254071080",
          "name":"Equinox Alignments in Siwa Oasis",
          "rsvp_limit":30,
          "status":"upcoming",
          "time":1537516800000,
          "local_date":"2018-09-21",
          "local_time":"10:00",
          "updated":1535123783000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":6,
          "venue":{  
             "id":25098480,
             "name":"Siwa Oasis",
             "lat":0.0,
             "lon":0.0,
             "repinned":false,
             "address_1":"Western Sahara, Egypt ",
             "city":"Siwa",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1481633751000,
             "name":"The Fountain of Light",
             "id":21562922,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"The-Fountain-of-Light",
             "who":"Light Sparkles",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/The-Fountain-of-Light/events/254071080/",
          "description":"<p>Equinox Alignments and Full Moon Desert Experience in Siwa Oasis. </p> <p>New Discovery - Equinox Alignments in Egyptian Sahara Desert</p> <p>The most Auspicious Spiritual Event</p> <p>Be among the first in thousands of years to view the Equinox Sunrise Alignment from the mysterious ancient Timasirayn Temple with the Oracle sight in Siwa Oasis. </p> <p>The Master Key to Everything is to be at the most Auspicious Place during the most Auspicious Time.</p> <p>Bathe in the most Auspicious Frequency<br/>Receive the most Auspicious Light Codes<br/>Experience the most Auspicious Alignment<br/>Retreat in the most Auspicious Environment<br/>Embody the most Auspicious Energy<br/>Open to your most Auspicious Potential<br/>Manifest the most Auspicious Reality<br/>Make the most Auspicious Breakthrough</p> ",
          "visibility":"public"
       },
       {  
          "created":1534432977000,
          "duration":10800000,
          "id":"253844999",
          "name":"Build E2E Automation Tests Pipeline (UI + API + Performance testing)",
          "rsvp_limit":50,
          "status":"upcoming",
          "time":1538146800000,
          "local_date":"2018-09-28",
          "local_time":"17:00",
          "updated":1534433285000,
          "utc_offset":7200000,
          "waitlist_count":9,
          "yes_rsvp_count":50,
          "group":{  
             "created":1493243139000,
             "name":"Cairo Testing Meetup",
             "id":23446514,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Testing-Meetup",
             "who":"Awesome Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Testing-Meetup/events/253844999/",
          "description":"<p>Building end-to-end automation tests pipeline (UI + API + Performance testing) with Serenity, Selenium Webdriver , Rest Assured, Taurus and Jenkins Blue ocean.</p> ",
          "visibility":"public"
       },
       {  
          "created":1533124649000,
          "duration":14400000,
          "id":"253371533",
          "name":"Tafra Meetup #15: Culture in Tech Companies",
          "rsvp_limit":50,
          "status":"upcoming",
          "time":1535731200000,
          "local_date":"2018-08-31",
          "local_time":"18:00",
          "updated":1535039975000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":21,
          "venue":{  
             "id":25752148,
             "name":"AlMaqarr Coworking Space (The Greek Campus - Downtown)",
             "lat":30.037214279174805,
             "lon":31.24540138244629,
             "repinned":false,
             "address_1":"28 Falaki St., Bab El Louk Cairo, Egypt 11511",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1507207135000,
             "name":"#TafraMeetup",
             "id":26161007,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"tafranetwork",
             "who":"Techies",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/tafranetwork/events/253371533/",
          "description":"<p>This is the first #TafraMeetup of series of Tafra \"Management &amp; Process Improvement\" Community.</p> <p>Only Tafra Meetup attendees are eligible to join the community and enjoy the network, discussions and shared info.</p> <p>If you are reading this, it means you are interested in Tech .. So whatever your work domain/role is, This #TafraMeetup is a real added-value and eye opening meetup you truly do not want to miss!</p> <p>Egypt is facing a serious tech brain drain this period, Is companies culture has something to do with this? Is there a lack of knowledge with decision makers and tech-business owners?</p> <p>Do European and American Companies do something we do not know to set a tone/build a culture for their own companies? What are the factors should we lean on regarding high/low turn over?</p> <p>How to manage techies? Is the process different in startup than SME than corporates? \u2026 and many more questions/concerns.</p> <p>We will be tackling everything about this insightful topic by reputable agile coaches, tech-business owners and techies.</p> <p>Join 4 Hrs of #TafraMeetup to engage, learn and meet the community.</p> <p>- For whom this Meetup:<br/>1. Junior/Senior Developers/Software Engineers.<br/>2. CEOs.<br/>3. CTOs.<br/>4. Decision Makers in Tech Startups/SME/Corporates.<br/>5. Tech Recruiters.<br/>6. Tech Leads.<br/>7. HR/\u201dPeople Partner\u201d.<br/>8. Agile Coaches and Enthusiasts.<br/>9. Juniors and Seniors in Tech-Related Fields.<br/>10. Any Techie/Non Techie eager to know more about Building Culture in Tech Companies.</p> <p>- We will be tackling the following:<br/>1. Culture in Tech Startups Vs. Culture in Software Houses Vs. Culture in Corporates.<br/>2. Do Techies leave Companies nowadays? or Managers? Why they leave? Why they stay?<br/>3. How to decrease the tech brain drain?<br/>4. How to set tone/build culture for your company?<br/>5. What's happening Globally vs. Locally?<br/>6. Are we different than west companies? Should we?<br/>7. How to manage/lead tech people?<br/>8. There will be a room for attendees\u2019 questions, yet you can add them to the registration form and we will deliver them to the speakers.</p> <p>- Venue, Date, Time &amp; Duration:<br/>AlMaqarr - GrEEK Campus Branch \"Tahrir Sq.\"<br/>Friday[masked]<br/>(18:00 to 22:00)<br/>4 Essentials Hours for Tech-Business Owners, Agile Coaches, Developers, Tech Leads &amp; HR People.</p> <p>- Meetup Agenda:<br/>18:00-18:30 \u2026 Keynote, Ice Breaking &amp; Networking Activity<br/>18:30-20:00 \u2026 \"Creating High Performance Teams\" by Amr Elssamadisy - Know more: <a href=\"https://bit.ly/2vLCsWk\" class=\"linkified\">https://bit.ly/2vLCsWk</a><br/>20:00-20:20 \u2026 Snacks + Coffee Break<br/>20:20-22:00 \u2026 \"Culture in Tech Companies\" Panel Discussion Moderated and Participated by Gurus in Tech Field .. Check Event Wall to know more on them. <a href=\"https://www.facebook.com/events/284025259013655/?active_tab=discussion\" class=\"linkified\">https://www.facebook.com/events/284025259013655/?active_tab=discussion</a></p> <p>- Who\u2019re the Speakers?<br/>1) Amr Elssamadisy, Executive Agile Coach at Samadisy, Inc.<br/>2) Rami ElSawy, Founder and Managing Director at The Elephant Tech. (Panelist)<br/>3) Nora Abdelrahman, People and Culture Manager at Eventtus. (Panelist)<br/>We will be revealing other speakers' names veeeery soon. Till then, Guess who? ;)</p> <p>- How to attend?<br/>Two stages, Registration, and Investment.<br/>1) Registration<br/>through here: <a href=\"https://goo.gl/forms/wOBi3PBgmwoqjTpl2\" class=\"linkified\">https://goo.gl/forms/wOBi3PBgmwoqjTpl2</a></p> <p>2) Submit your investment<br/>From here: <a href=\"https://paymestore.co/A085627\" class=\"linkified\">https://paymestore.co/A085627</a></p> <p>- Investment Fees:<br/>★Early Bird Ticket: 125 EGP - till Monday[masked]<br/>★Late Owl Ticket: 160 EGP - Starting from Tuesday[masked]</p> <p>P.S. Registration for the Meetup is a MUST. We have very limited seats due to the capacity of the venue .. so hurry up reserving your seat in the early bird period!</p> <p>Materials and Talks will be conducted in Arabic/English.</p> <p>For any inquiries, please call us at [masked]</p> <p>More info on Why to attend? and who are we?, check out this link:<br/><a href=\"https://www.facebook.com/events/284025259013655/\" class=\"linkified\">https://www.facebook.com/events/284025259013655/</a></p> <p>Tafra - Empowering Techies</p> ",
          "how_to_find_us":"You can ask the Campus security also Where's AlMaqarr",
          "visibility":"public"
       },
       {  
          "created":1533116025000,
          "duration":7200000,
          "id":"253369123",
          "name":"Healthcare scenarios and solutions (Cairo Festival city)",
          "status":"upcoming",
          "time":1535792400000,
          "local_date":"2018-09-01",
          "local_time":"11:00",
          "updated":1533116025000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":7,
          "group":{  
             "created":1533049787000,
             "name":"Healthcare Happiness Egypt",
             "id":29403829,
             "join_mode":"approval",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Healthcare-Happiness-Egypt",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Healthcare-Happiness-Egypt/events/253369123/",
          "visibility":"public"
       },
       {  
          "created":1535216033000,
          "duration":10800000,
          "id":"fhwkdqyxmbdb",
          "name":"English Club with Onsy By SWAP* ",
          "status":"upcoming",
          "time":1535904000000,
          "local_date":"2018-09-02",
          "local_time":"18:00",
          "updated":1535216033000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":4,
          "venue":{  
             "id":13264492,
             "name":"Downtown",
             "lat":30.04442024230957,
             "lon":31.2357120513916,
             "repinned":false,
             "address_1":"Decieded Later!",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1455120743000,
             "name":"Cairo Language Freaks",
             "id":19550132,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Language-Freaks",
             "who":"language freak",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Language-Freaks/events/254099387/",
          "description":"<p>الكورسات مش بتعلم لغه<br/>اللغة ممارسة، بيقولولك ممكن تقف تكلم نفسك في المراية، .. أو احفظ أغنية انجليش وغنيها بصوت عالي عشان تعود لسانك علي النطق الصحيح.. أو حتى إتفرج على فيلم بتحبه من بس بدل الترجمة حط English subtitles اللي هو نص الحوار بتاع الفيلم أو المسلسل كل يوم ، لحد ما تحفظ الحوار ..</p> <p>بس ساعات كتير ده مابيبقاش كفاية، بنحتاج دايماً حد يوجهنا.. و نبقى ملتزمين تجاه حاجة معينة عشان نمارس اللغة كل يوم، لحد ما تبقى جزء مننا.. عشان كده عملنالكوا SWAP English Club</p> <p>لو حابب تتكلم انجليزي خارج نطاق التعليم العادي عشان لو قابلت أجانب تعرف تكلمهم بالانجليزي English Conversation Club. هنتقابل كل يوم أحد نتكلم مع بعض انجليزي لمدة ساعتين متواصلين. هانتكلم عن كل حاجة بحيث نعرف نستعمل الانجليزي في كل مواقف الحياة. الدعوة عامة لكل الناس كبير وصغير اتخرجت أو ما اتخرجتش ما يهمش المهم انك جاي تتعلم وخصوصاً للمبتدئين في اللغة او من يجد صعوبة في ممارسة اللغة الإنجليزية مع الآخرين<br/>ننتظركم في جراج المحروسة 2 شارع القاضي الفاضل نتفرع من صبري ابو علم وسط البلد - الدور الاول بعد الارضي<br/>Mohamed onsy will meet you every Sunday inside garage el mahrousa co-working space at 6 p.m</p> <p>Facebook page :<br/><a href=\"https://www.facebook.com/GarageElMahrousa/\" class=\"linkified\">https://www.facebook.com/GarageElMahrousa/</a></p> <p>2 Al Qadi Al Fadel, off Sabry Abo Allam St., Downtown</p> <p>Feel free to call :<br/>Mohamed onsy<br/>[masked]<br/>Or<br/>Mahmoud Hamouda<br/>[masked]<br/>Whats App. No. :[masked]</p> <p>See you All</p> ",
          "visibility":"public"
       },
       {  
          "created":1534589124000,
          "duration":21600000,
          "id":"253897884",
          "name":"Study osteopathy in Middle East ",
          "rsvp_limit":25,
          "status":"upcoming",
          "time":1535745600000,
          "local_date":"2018-08-31",
          "local_time":"22:00",
          "updated":1534589228000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":7,
          "venue":{  
             "id":25071421,
             "name":"Osteophysio / OsteoEgypt Clinic ",
             "lat":30.055130004882812,
             "lon":31.19911003112793,
             "repinned":true,
             "address_1":"5 Lebanon st ",
             "city":"Al Muhandisin",
             "country":"EG",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1487762221000,
             "name":"Osteopathy & Osteopathic Medicane استوباثي",
             "id":22567008,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Osteopathy-Osteopathic-Medicane-استوباثي",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Osteopathy-Osteopathic-Medicane-%D8%A7%D8%B3%D8%AA%D9%88%D8%A8%D8%A7%D8%AB%D9%8A/events/253897884/",
          "visibility":"public"
       },
       {  
          "created":1535475960000,
          "duration":7200000,
          "id":"254178431",
          "name":"Think and Grow Rich - Meetup #2",
          "status":"upcoming",
          "time":1535731200000,
          "local_date":"2018-08-31",
          "local_time":"18:00",
          "updated":1535554610000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":3,
          "group":{  
             "created":1532883360000,
             "name":"Think and Grow Rich - Book Club",
             "id":29387026,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"ThinkandGrowRichCairo",
             "who":"Thinkers",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/ThinkandGrowRichCairo/events/254178431/",
          "description":"<p>Welcome to our second meetup! If this is your first time joining us, don't worry, you're right on time. Take a look at the first chapter and think about some of the questions asked in first chapter of the Action Guide. To find the book, simply google \"Think and Grow Rich pdf,\" and for the Action Guide, search \"Think and Grow Rich Action Guide pdf.\" We look forward to seeing you there!</p> ",
          "visibility":"public"
       },
       {  
          "created":1535192818000,
          "duration":10800000,
          "id":"254093643",
          "name":"Tafra Meetup #16: Design Systems & Prototyping Tools",
          "rsvp_limit":50,
          "status":"upcoming",
          "time":1536163200000,
          "local_date":"2018-09-05",
          "local_time":"18:00",
          "updated":1535297704000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":1,
          "venue":{  
             "id":25752148,
             "name":"AlMaqarr Coworking Space (The Greek Campus - Downtown)",
             "lat":30.037214279174805,
             "lon":31.24540138244629,
             "repinned":false,
             "address_1":"28 Falaki St., Bab El Louk Cairo, Egypt 11511",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1507207135000,
             "name":"#TafraMeetup",
             "id":26161007,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"tafranetwork",
             "who":"Techies",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/tafranetwork/events/254093643/",
          "description":"<p>This is the 3rd #TafraMeetup of series of Tafra \"Design Methodologies &amp; Frameworks\" Community. (<a href=\"https://www.facebook.com/groups/1628628113850918/\" class=\"linkified\">https://www.facebook.com/groups/1628628113850918/</a>)</p> <p>Only Tafra Meetup attendees are eligible to join the community and enjoy the network, discussions and shared info.<br/>(The previous meetup link: <a href=\"https://www.facebook.com/events/256757658391431/\" class=\"linkified\">https://www.facebook.com/events/256757658391431/</a> )</p> <p>Design Systems are very essential and crucial set of principles needed for Designers, Front End Enthusiasts, Product Managers and Tech-Business Owners.</p> <p>The concept of Design Systems has been around for some time, But recently only have some companies given attention to design systems as they realized their designs weren\u2019t scaling as quickly as their businesses like Airbnb and Uber.</p> <p>Are they like Pattern Libraries? Are they Front-End Frameworks? Are there ways to measure the results? Are there global standards?</p> <p>Also, As a Designer, What are the best Prototyping Tools for you? Are there factors you consider while using the design tool you choose? What about the hype around Framer X From Google, Facebook and Airbnb Gurus?</p> <p>Let's discuss, share and discover all of the mentioned above together in a real value added 3 Hrs #TafraMeetup.</p> <p>- For whom this Meetup:<br/>1. Junior UI - UX Designers.<br/>2. Senior UI - UX Designers.<br/>3. Product Managers.<br/>4. CPOs.<br/>5. CEOs.<br/>6. Tech-Business Owners<br/>7. Front End Developers/Enthusiasts<br/>8. Anyone who wants to know more about Design Systems.<br/>9. Anyone who wants to know more on Prototyping and Tools.<br/>10. Anyone who wants to try the new Framer X.</p> <p>- We will be tackling through 2 engaging sessions/min workshops the following:<br/>1. Design Systems (Why?, What?, How?, Case Studies and Insightful Discussions/Tips)<br/>2. Prototyping Tools (Why?, What?, How?, Insights and Comparison)<br/>3. Let\u2019s Deep into the new Framer X (Does it worth the global hype around it?)<br/>4. There will be a room for attendees\u2019 questions, yet you can add them to the registration form and we will deliver them to the speakers.</p> <p>- Venue, Date, Time &amp; Duration:<br/>AlMaqarr - GrEEK Campus Branch \"Tahrir Sq.\"<br/>Tuesday[masked]<br/>(18:00 to 21:00)<br/>3 Essentials Hours for Designers, Product Managers &amp; Business Owners.</p> <p>- Meetup Agenda:<br/>18:00-18:30 \u2026 Keynote, Ice Breaking &amp; Networking Activity<br/>18:30-20:00 \u2026 Design Systems, Prototyping &amp; Prototyping Tools<br/>20:00-20:30 \u2026 Snacks + Coffee Break + Networking Continued<br/>20:00-21:00 \u2026 \"Hands-on mini-workshop on Framer X\" by Zero, Know more:</p> <p>- Who\u2019re the Speakers?<br/>1) Mohammed Morsi (Zero), Product Designer at OneFootball<br/>We\u2019ll be revealing other speaker(s) name(s) veeeeery soon, until then... Guess who? ;)</p> <p>- How to attend?<br/>Two stages, Registration, and Investment/Payment.<br/>1) Registration<br/>through here: <a href=\"https://goo.gl/forms/n2BFWqUeFycWQDcw2\" class=\"linkified\">https://goo.gl/forms/n2BFWqUeFycWQDcw2</a></p> <p>2) Submit your investment<br/>From here: <a href=\"https://paymestore.co/A085629\" class=\"linkified\">https://paymestore.co/A085629</a></p> <p>- Investment Fees:<br/>★Early Bird Ticket: 125 EGP - till Saturday[masked]<br/>★Late Owl Ticket: 160 EGP - Starting from Sunday[masked]</p> <p>P.S. Registration for the Meetup is a MUST. We have very limited seats due to the capacity of the venue .. so hurry up reserving your seat in the early bird period!</p> <p>Materials and Talks will be conducted in Arabic/English.</p> <p>For any inquiries, please call us at [masked]</p> <p>More info on Why to attend? and who are we?, check out this link:<br/><a href=\"https://www.facebook.com/events/284025259013655/\" class=\"linkified\">https://www.facebook.com/events/284025259013655/</a></p> <p>Tafra - Empowering Techies<br/>#Tafra #TafraMeetup</p> ",
          "how_to_find_us":"You can ask the Campus security also Where's AlMaqarr",
          "visibility":"public"
       },
       {  
          "created":1533995185000,
          "duration":10800000,
          "id":"253705004",
          "name":"DISOBEDIENCE - Screening & Discussion",
          "rsvp_limit":100,
          "status":"upcoming",
          "time":1536944400000,
          "local_date":"2018-09-14",
          "local_time":"19:00",
          "updated":1533995318000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":35,
          "venue":{  
             "id":25902734,
             "name":"george and dalia's place",
             "lat":30.05767822265625,
             "lon":31.192378997802734,
             "repinned":false,
             "address_1":"48 El-Quds El-Shareef",
             "address_2":"Mit Akaba",
             "city":"Al Agouzah",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1519467781000,
             "name":"Javaflix Cairo",
             "id":27631356,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Javaflix-Cairo",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Javaflix-Cairo/events/253705004/",
          "description":"<p>Ahwaflix is a free monthly movie discussion group. Together, we watch a movie and talk about it.</p> <p>Join us Friday September 14th as we watch and discuss:</p> <p>DISOBEDIENCE (2018) Rated R for strong sexuality<br/>A woman returns to her Orthodox Jewish community that shunned her for her attraction to a female childhood friend. Once back, their passions reignite as they explore the boundaries of faith and sexuality.</p> <p>Format of the evening:<br/>700 - 715 - Arrive and announcements<br/>715 - 910 - Movie Screening<br/>910 -920 - Break and voting for next months film<br/>920 - 1000 - Discussion</p> <p>Movie selection is based on member votes from our previous meetup.</p> <p>We will always meet on the 2nd Friday of every month.</p> <p>Contact me on whatsapp at[masked] for questions or location details</p> ",
          "how_to_find_us":"flat #8 whatsapp me at 01098794096",
          "visibility":"public"
       },
       {  
          "created":1528858761000,
          "duration":7200000,
          "id":"cfghvpyxmbgb",
          "name":"Casual Soccer",
          "rsvp_limit":15,
          "status":"upcoming",
          "time":1536087600000,
          "local_date":"2018-09-04",
          "local_time":"21:00",
          "rsvp_open_offset":"PT104H",
          "rsvp_close_offset":"PT8H",
          "updated":1528858762000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":1,
          "venue":{  
             "id":25456808,
             "name":"Champions Arena",
             "lat":0.0,
             "lon":0.0,
             "repinned":false,
             "address_1":"Sabil El Moameneen St. Off El Wafaa & El Amal St., Beside Veterans Association & Free Zone Madinet El-Nasr",
             "city":"Cairo",
             "country":"eg",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1475324437000,
             "name":"Casual Soccer Cairo",
             "id":20545672,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Casual-Soccer",
             "who":"Champs",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Casual-Soccer/events/254166003/",
          "description":"<p>PLEASE READ BEFORE SIGN IN</p> <p>- Sign in ASAP, with a maximum of 15 players (3 teams, 5-a-side). Game is On as long as there are more than 12 players.</p> <p>- Please be there 15 mins early, so that we are ready for kick off on time.</p> <p>Major game rules:</p> <p>1. No slide tackling.<br/>2. Winner to be decided by the final score at the end of a 8-minute game or 3 goals (Maximum 3 consecutive games for a team). Challenger wins a drawn game.<br/>3. Game stops right at the buzzer.</p> <p>Participation rules<br/>You will be banned from the group for the following reasons:</p> <p>1. If you sign up and don't show up for any reason.<br/>2. If you sign up and cancel less than 24 hours before game (2 times)<br/>3. Offensive behavior (there is no tolerance for that)</p> <p>Enjoy the game :)</p> <p><a href=\"https://www.facebook.com/CairoCasualSoccer/\" class=\"linkified\">https://www.facebook.com/CairoCasualSoccer/</a></p> <p>Ze [masked])</p> ",
          "how_to_find_us":"https://www.google.com/maps?f=q&hl=en&q=30.035640,31.348654",
          "visibility":"public"
       },
       {  
          "created":1515203649000,
          "duration":7200000,
          "id":"hxgzdpyxmbcc",
          "name":"Does Osteopathy Fillis the Gap in medicine?",
          "rsvp_limit":30,
          "status":"upcoming",
          "time":1537524000000,
          "local_date":"2018-09-21",
          "local_time":"12:00",
          "rsvp_close_offset":"PT167H",
          "updated":1515203649000,
          "utc_offset":7200000,
          "waitlist_count":0,
          "yes_rsvp_count":2,
          "venue":{  
             "id":25071421,
             "name":"Osteophysio / OsteoEgypt Clinic ",
             "lat":30.055130004882812,
             "lon":31.19911003112793,
             "repinned":false,
             "address_1":"5 Lebanon st ",
             "city":"Al Muhandisin",
             "country":"EG",
             "localized_country_name":"Egypt"
          },
          "group":{  
             "created":1515202974000,
             "name":"Cairo Osteopathy Meetup",
             "id":27063920,
             "join_mode":"open",
             "lat":30.059999465942383,
             "lon":31.25,
             "urlname":"Cairo-Osteopathy-Meetup",
             "who":"Members",
             "localized_location":"Cairo, Egypt",
             "region":"en_US",
             "timezone":"Africa/Cairo"
          },
          "link":"https://www.meetup.com/Cairo-Osteopathy-Meetup/events/252682865/",
          "description":"<p>\u2022 What we'll do<br/>we will Discuss a different Options for Egyptian Doctors and physical therapist to study Osteopathy in more Cost efficient way without compromising the Quality.</p> <p>\u2022 What to bring<br/>Clear Mind</p> <p>\u2022 Important to know<br/>NA</p> ",
          "visibility":"public"
       }
    ]
 }